<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Properties\launchSettings.json" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Properties\launchSettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>Never</CopyToPublishDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="9.3.2" />
        <PackageReference Include="Cogito.Extensions.Logging.Serilog.Autofac" Version="3.0.3" />
        <PackageReference Include="Cogito.Serilog.Autofac" Version="4.0.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cogito.AspNetCore.Autofac\Cogito.AspNetCore.Autofac.csproj" />
        <ProjectReference Include="..\Cogito.AspNetCore\Cogito.AspNetCore.csproj" />
    </ItemGroup>

</Project>
