<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netcoreapp3.0</TargetFrameworks>
        <Description>Various utilities and extensions for working with Autofac and ASP.Net Core.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Cogito.Autofac" Version="6.1.3" />
        <PackageReference Include="Cogito.Autofac.DependencyInjection" Version="6.1.3" />
        <PackageReference Include="Cogito.Extensions.Logging.Autofac" Version="3.0.3" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' != 'netcoreapp3.0' ">
        <PackageReference Include="Microsoft.AspNetCore" Version="2.3.13" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cogito.AspNetCore\Cogito.AspNetCore.csproj" />
    </ItemGroup>

</Project>
